### ISSUE TITLE
Linkedin Link wont work in the Readme.md file

### ISSUE THREAD

**Issue by AminTaheri23** [GreyNewfie/GreyNewfie#1]
Hey,

Amazing banner btw :)

**Comment by GreyNewfie** [comment]
Thanks for letting me know that, Amin! I also appreciate the practice using issues. It's something I've been meaning to start using more, but haven't.

Thanks! I took the banner photo at a park on the West Coast while camping.

**Comment by GreyNewfie** [comment]
Updated LinkedIn link
